services:
  mirero.pwm.infra.nexus:
    image: sonatype/nexus3:latest
    container_name: mirero.pwm.infra.nexus
    ports:
      - "8070:8081"
    volumes:
      - nexus-data:/nexus-data
    restart: unless-stopped

volumes:
  nexus-data:
