version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: architecture_study
      POSTGRES_USER: mirero
      POSTGRES_PASSWORD: rlawlstn
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - mirero

networks:
  mirero:
    external: true
    name: mirero
